### ISSUE TITLE
Cannot build Vaadin Flow with Java 17 - PermittedSubclasses requires ASM9

### ISSUE THREAD

**Issue by rmuller** [vaadin/flow#12136]
When trying to create a production build of our Vaadin application we encounter the following error: 

`Failed to execute goal com.vaadin:vaadin-maven-plugin:14.7.2:build-frontend (default) on project myvaadin: Execution default of goal com.vaadin:vaadin-maven-plugin:14.7.2:build-frontend failed: PermittedSubclasses requires ASM9`

Environment:

- Amazon corretto JDK 17
- Maven 3.8.2
- Debian 11

Looks similar to https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/server/frontend/scanner/FrontendAnnotatedClassVisitor.java. So bytebuddy/asm must by upgraded to use `Opcodes.ASM9` instead of `Opcodes.ASM8` (so needs asm version 9.1, see https://asm.ow2.io/versions.html)

Also see

**Comment by rmuller** [comment]
First tried to build a trivial Vaadin Flow app with the same tooling and Java 17 compiled libraries (including `record` types). Could not reproduce this error.

After that tried to isolate the cause of this problem but did not succeed. It is this code fragment in `net.bytebuddy.jar.asm.ClassVisitor` that causes the error:

    /**
     * Visits a permitted subclasses. A permitted subclass is one of the allowed subclasses of the
     * current class.
     *
     * @param permittedSubclass the internal name of a permitted subclass.
     */
    public void visitPermittedSubclass(final String permittedSubclass) {
      if (api < Opcodes.ASM9) { // <===== HERE
        throw new UnsupportedOperationException("PermittedSubclasses requires ASM9");
      }
      if (cv != null) {
        cv.visitPermittedSubclass(permittedSubclass);
      }
    }

Tried to change `com.vaadin.flow.server.frontend.scanner.FrontendDependencies` to get more meaningful error messages, but i am not able to build Vaadin (see https://github.com/vaadin/flow/issues/12205)

    FrontendClassVisitor visitor = new FrontendClassVisitor(className,  endPoint, themeScope);
    try (InputStream is = url.openStream()) {
        ClassReader cr = new ClassReader(is);
        cr.accept(visitor, ClassReader.EXPAND_FRAMES);
    } catch (RuntimeException ex) { // <==== need this for better debugging
        log().error("Exception while visiting class {}: {}", className, ex);
    }

To be continued ....

**Comment by knoobie** [comment]
That probably comes from the usage of `Opcodes.ASM8` inside flow - it's highly possible that it has to be updated to ASM9, like done from ASM7 to ASM8 to support records https://github.com/vaadin/flow/pull/10979

**Comment by rmuller** [comment]
Yes, that is also my conclusion, see first comment.

**Comment by mstahv** [comment]
Are you @rmuller planning to continue looking into this? I quickly added JEP409 examples to my test setup, but still compiles fine. Maybe those should also contain same Vaadin code 🤔

**Comment by rmuller** [comment]
@mstahv for sure!

> To be continued ....

**Comment by rmuller** [comment]
Got it.

Add this to your code to see the magic

    public enum AnEnum {
        
        ONE() {
            @Override
            public String digit() {
                return "1";
            }
        };

        public abstract String digit();
    }

Explanation can be found here: https://issues.apache.org/jira/browse/GROOVY-10194

**Comment by mstahv** [comment]
Thanks, verified. With Vaadin 22 that works fine, but bugs with Vaadin 14. ASM comes to use through, byte-buddy, so we need to update its version in V14 branch.

**Comment by mstahv** [comment]
The fix ought to fit into next maintenance release (14.7.4) soonish.

**Comment by Artur-** [comment]
This was fixed, not sure why this issue was left open

**Comment by rmuller** [comment]
Yes byte-buddy is now up-to-date, but the latest version of flow-server (2.7.6) still uses ASM8 in `FrontendClassVisitor`! The code in github is already updated to ASM9, but it is not landed yet in the distributed jars for flow 14!
Some issues still exits

**Comment by esommars** [comment]
Still broken  with 14.8.0 yes.

**Comment by mstahv** [comment]
There hasn't yet been any 14.x releases since the latest fixes has been landed to that branch. There will be 14.8.1 most likely next week.

**Comment by rmuller** [comment]
@esommars I can confirm that this issue is now completely resolved. All my Java 17 based code (using a lot of Java 11+ functionality and language enhancements) are working perfectly! Version 14.8.1 needed indeed.

**Comment by esommars** [comment]
@ rmuller Super great to hear! Will use compile level 17 now. Happy new years!
