### ISSUE TITLE
Gradle Incremental Build for `vaadinBuildFrontend` task

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#17354]
### Describe your motivation

Vaadin Gradle plugin task `vaadinBuildFrontend` can be skipped during project build for production in case of all the inputs and outputs haven't been changed since the last production build. This saves time when developers want to run the application locally, e.g. for running integration tests, and allows to skip the most time-consuming part - bundle build. 

Running production build on CI servers usually require a new bundle build, so this feature isn't much useful there.

### Describe the solution you'd like

Implement [Gradle Incremental Build](https://docs.gradle.org/current/userguide/incremental_build.html) feature for `vaadinBuildFrontend` to let Gradle skip this task if a prod bundle files are already created on the previous build and not changed, as well as project configuration not changed since last run.

### Describe alternatives you've considered

Skipping the bundle build can be done in a general way for all build tools, including Maven, but this would need to implement "incremental build" feature by our-selfs, in Gradle it is available out-of-the-box.

### Additional context

This is an extension of the idea implemented within (this issue)[https://github.com/vaadin/flow/issues/15342] for `vaadinPrepareFrontend`.

**Comment by mshabarov** [comment]
Related https://github.com/vaadin/flow/issues/16886

**Comment by benstpierre** [comment]
This would relieve a huge pain point for us.

**Comment by tarekoraby** [comment]
@benstpierre, to clarify, what is the pain point? Is the creation of production builds time-sensitive for you?

**Comment by steve-todorov** [comment]
Hey @tarekoraby ,

This would greatly improve the DevOps experience. When you develop a pipeline or do some Gradle build tasks that are not directly related to Vaadin you always need to wait for the `vaadinBuildFrontend` to finish even if you haven't touched anything on that front. In our case the `vaadinBuildFrontend` takes about 3 minutes every time which is obviously wasted time that can be eliminated with Gradle's cache.

**Comment by mvysny** [comment]
Commencing work in the branch https://github.com/vaadin/flow/tree/feat/17354-incremental-build

**Comment by mshabarov** [comment]
We have implemented another common improvement for prod bundle to be re-used, see https://github.com/vaadin/flow/issues/16886. This is included into Vaadin 24.3. Let's see how much this improves developer experience for `vaadinBuildFrontend` as I assume this is most time-consuming part - to build the bundle.

**Comment by steve-todorov** [comment]
That is great news! Looking forward to test this when `24.3` comes out :)

**Comment by benstpierre** [comment]
Is this abandoned?

**Comment by mshabarov** [comment]
@benstpierre thanks for the ping. I thought that after https://github.com/vaadin/flow/issues/16886 the long running build problem would be almost covered, but the Gradle Incremental build in general is a powerful feature and may help with other aspects, thus, I think it makes sense to get back to this topic. Hopefully AI can help us make the routine changes based on `prepare-frontend` implementation.

**Comment by benstpierre** [comment]
Hey — wanted to circle back on this. We're on 24.9.12 and `vaadinBuildFrontend` is still not Gradle-cacheable. We also looked at the `@CacheableTask` work in PR #23884 (targeting 25.0) and unfortunately it doesn't fully solve the problem either. Here's what we found by auditing the plugin source:

**The root cause:** `vaadinBuildFrontend` writes Vite output to `build/resources/main/META-INF/VAADIN/webapp/` — the same directory owned by Gradle's `processResources`. This prevents declaring it as a task output (overlapping-outputs validation). Without declared outputs, Gradle's build cache can't restore the files on a cache hit.

**Why `@CacheableTask` in 25.0 is incomplete:** PR #23884 adds `@CacheableTask` and declares `@Input`/`@Classpath` annotations, which enables **local up-to-date checking** (great!). But the Vite output directory (`frontendOutputDirectory`) is not declared as `@OutputDirectory` — because it can't be, due to the overlap. So on a **build cache restore** (the CI use case), the task is skipped but the frontend files aren't restored. The jar ships without `index.html`.

**The one-line fix:** Change the default `frontendOutputDirectory` from `build/resources/main/META-INF/VAADIN/webapp/` to something outside processResources territory — e.g. `build/vaadin-frontend/META-INF/VAADIN/webapp/`. Then it can be declared as `@OutputDirectory` and Gradle caches it natively. The property already exists in `VaadinFlowPluginExtension` — it just defaults to the overlap zone.

**The catch:** `servletResourceOutputDirectory()` in `GradlePluginAdapter` is hardcoded to `build/resources/main/META-INF/VAADIN/` (when `isBeforeProcessResources=false`), and `ProdBundleUtils.compressBundle()` compresses from that directory. So redirecting `frontendOutputDirectory` alone breaks the bundle — both need to move together, and the jar task needs a `from()` wired automatically by the plugin.

**Our workaround for anyone stuck on 24.x:** We declare `src/main/bundles/` as the task output (which contains `prod.bundle`), then `zipTree()` it in the jar task to unpack it at `META-INF/VAADIN/`. We're unzipping the zip that `compressBundle()` created from the files we can't cache directly. Details + A/B benchmarks: https://github.com/galateatech/waste-coordinator/pull/10283

Happy to contribute a PR if the team points us in the right direction.

**Comment by mcollovati** [comment]
@benstpierre contributions are more than welcome, thanks!
I propose to create a new ticket based on your findings and move the discussion there.

**Comment by mshabarov** [comment]
Please note that this feature was not back-ported to Vaadin 25.0 and 25.1, but only planned for 25.2.
