### ISSUE TITLE
flow-build-info.json isn't found in production build on web logic

### ISSUE THREAD

**Issue by SebastianKuehnau** [vaadin/flow#6965]
After building a WAR for PRODUCTION and deploying on a weblogic server the following error message appears:

`java.lang.IllegalStateException: Unable to determine mode of operation. To use npm mode, ensure 'flow-build-info.json' exists on the classpath. With Maven, this is handled by the 'prepare-frontend' goal. To use compatibility mode, add the 'flow-server-compatibility-mode' dependency. If using Vaadin with Spring Boot, instead set the property 'vaadin.compatibilityMode' to 'true' in 'application.properties'.` 

It seems the `flow-build-info.json` can't be found, but when checking the war file it is located in `/WEB-INF/classes/META-INF/VAADIN/config/`.

Analyzing the `DeploymentConfigurationFactory` it tries to open the file in `/META-INF/VAADIN/`

**Comment by denis-anisimov** [comment]
Could you please provide exact steps how can I reproduce it  (creating a project)?
Can I use skeleton-starter project for this ?
Or could you attach a project which I may use to reproduce?

**Comment by SebastianKuehnau** [comment]
I took a my-starter-project with the latest Vaadin version 14.0.13 and build it with production-profile. In the profile description of the production profile I added the `<vaadin.compatibilityMode>false</vaadin.compatibilityMode>` definition.

I deployed the application on a WebLogic Server (v 12.2.1.3.) and I'm still getting the following error message:
`<Nov 21, 2019 3:10:46,190 PM GMT> <Error> <HTTP> <BEA-101017> <[ServletContext@94070817[app:my-starter-project-1.0-SNAPSHOT module:my-starter-project-1.0-SNAPSHOT.war path:null spec-version:3.1]] Root cause of ServletException.
java.lang.IllegalStateException: Unable to determine mode of operation. To use npm mode, ensure 'flow-build-info.json' exists on the classpath. With Maven, this is handled by the 'prepare-frontend' goal. To use compatibility mode, add the 'flow-server-compatibility-mode' dependency. If using Vaadin with Spring Boot, instead set the property 'vaadin.compatibilityMode' to 'true' in 'application.properties'.
at com.vaadin.flow.server.DeploymentConfigurationFactory.verifyMode(DeploymentConfigurationFactory.java:382)
at com.vaadin.flow.server.DeploymentConfigurationFactory.lambda$readBuildInfo$1ac205d3$1(DeploymentConfigurationFactory.java:230)
at com.vaadin.flow.server.DefaultDeploymentConfiguration.checkCompatibilityMode(DefaultDeploymentConfiguration.java:275)
at com.vaadin.flow.server.DefaultDeploymentConfiguration.<init>(DefaultDeploymentConfiguration.java:120)
at com.vaadin.flow.server.VaadinServlet.createDeploymentConfiguration(VaadinServlet.java:166)
Truncated. see log file for complete stacktrace
> `

**Comment by denis-anisimov** [comment]
Project from here is used: http://vaadin.com/start

It might be it's the same as https://github.com/vaadin/skeleton-starter-flow or not....

**Comment by SebastianKuehnau** [comment]
I tried it again with the. skelaton-starter-flow, build it with production and compatibiltyMode = false and I'm still getting the same error message:
`<Nov 21, 2019 3:41:42,826 PM GMT> <Notice> <WebLogicServer> <BEA-000360> <The server started in RUNNING mode.> 
<Nov 21, 2019 3:41:42,852 PM GMT> <Notice> <WebLogicServer> <BEA-000365> <Server state changed to RUNNING.> 
<Nov 21, 2019 3:46:45,835 PM GMT> <Notice> <JMX> <BEA-149535> <JMX Resiliency Activity Server=AdminServer : Initializing callbacks> 
<Nov 21, 2019 3:46:45,849 PM GMT> <Notice> <JMX> <BEA-149535> <JMX Resiliency Activity Server=AdminServer : Added MBeanServerConnection in DomainRuntimeServiceMBean > 
<Nov 21, 2019 3:46:45,861 PM GMT> <Notice> <JMX> <BEA-149535> <JMX Resiliency Activity Server=AdminServer : Callback is done> 
<Nov 21, 2019 3:46:45,878 PM GMT> <Notice> <JMX> <BEA-149535> <JMX Resiliency Activity Server=AdminServer : Connection already exists for the server. Did not attempt to connect to the server> 
<Nov 21, 2019 3:46:49,600 PM GMT> <Notice> <JMX> <BEA-149535> <JMX Resiliency Activity Server=All Servers : Resolving connection list DomainRuntimeServiceMBean> 
[[STANDBY] ExecuteThread: '1' for queue: 'weblogic.kernel.Default (self-tuning)'] INFO com.vaadin.flow.server.osgi.OSGiAccess - Unable to detect used OSGi framework version due to null
[[STANDBY] ExecuteThread: '1' for queue: 'weblogic.kernel.Default (self-tuning)'] INFO com.vaadin.flow.server.startup.ServletDeployer - Automatically deploying Vaadin servlet with name com.vaadin.flow.server.startup.ServletDeployer to /*
<Nov 21, 2019 3:54:07,592 PM GMT> <Error> <HTTP> <BEA-101017> <[ServletContext@1498388454[app:project-base-1.0-SNAPSHOT module:project-base-1.0-SNAPSHOT.war path:null spec-version:3.1]] Root cause of ServletException.
java.lang.IllegalStateException: Unable to determine mode of operation. To use npm mode, ensure 'flow-build-info.json' exists on the classpath. With Maven, this is handled by the 'prepare-frontend' goal. To use compatibility mode, add the 'flow-server-compatibility-mode' dependency. If using Vaadin with Spring Boot, instead set the property 'vaadin.compatibilityMode' to 'true' in 'application.properties'.
at com.vaadin.flow.server.DeploymentConfigurationFactory.verifyMode(DeploymentConfigurationFactory.java:382)
at com.vaadin.flow.server.DeploymentConfigurationFactory.lambda$readBuildInfo$1ac205d3$1(DeploymentConfigurationFactory.java:230)
at com.vaadin.flow.server.DefaultDeploymentConfiguration.checkCompatibilityMode(DefaultDeploymentConfiguration.java:275)
at com.vaadin.flow.server.DefaultDeploymentConfiguration.<init>(DefaultDeploymentConfiguration.java:120)
at com.vaadin.flow.server.VaadinServlet.createDeploymentConfiguration(VaadinServlet.java:166)
Truncated. see log file for complete stacktrace
> 
<Nov 21, 2019 3:54:15,047 PM GMT> <Error> <HTTP> <BEA-101017> <[ServletContext@1498388454[app:project-base-1.0-SNAPSHOT module:project-base-1.0-SNAPSHOT.war path:null spec-version:3.1]] Root cause of ServletException.
java.lang.IllegalStateException: Unable to determine mode of operation. To use npm mode, ensure 'flow-build-info.json' exists on the classpath. With Maven, this is handled by the 'prepare-frontend' goal. To use compatibility mode, add the 'flow-server-compatibility-mode' dependency. If using Vaadin with Spring Boot, instead set the property 'vaadin.compatibilityMode' to 'true' in 'application.properties'.
at com.vaadin.flow.server.DeploymentConfigurationFactory.verifyMode(DeploymentConfigurationFactory.java:382)
at com.vaadin.flow.server.DeploymentConfigurationFactory.lambda$readBuildInfo$1ac205d3$1(DeploymentConfigurationFactory.java:230)
at com.vaadin.flow.server.DefaultDeploymentConfiguration.checkCompatibilityMode(DefaultDeploymentConfiguration.java:275)
at com.vaadin.flow.server.DefaultDeploymentConfiguration.<init>(DefaultDeploymentConfiguration.java:120)
at com.vaadin.flow.server.VaadinServlet.createDeploymentConfiguration(VaadinServlet.java:166)
Truncated. see log file for complete stacktrace
> `

**Comment by sandronm** [comment]
We are facing exactly the same issue and we are also using Weblogic.
@SebastianKuehnau could you try with vaadin version **14.0.7** ? 
We don't have the issue with this version but we have it with 14.0.13 and 14.0.14 (we didn't test with other versions)

**Comment by mvysny** [comment]
I can reproduce this issue easily with my https://github.com/mvysny/vaadin14-embedded-jetty project:

* By default it uses 14.0.12 and it works: build the project with `mvn -C clean package -Pproduction` then go to `target/` and run `java -jar vaadin14-embedded-jetty-1.0-SNAPSHOT-uberjar.jar` and browse to localhost:8080 -  everything works.
* However, edit the pom.xml and set vaadin version to 14.0.13 or 14.0.14, build the project with `mvn -C clean package -Pproduction` then go to `target/` and run `java -jar vaadin14-embedded-jetty-1.0-SNAPSHOT-uberjar.jar` and browse to localhost:8080 - it will crash.

The `META-INF/VAADIN/config/flow-build-info.json` exists in both jars, however it seems it's being ignored somehow in 14.0.13 and 14.0.14...

**Comment by mvysny** [comment]
There is a subtle difference in `DeploymentConfigurationFactory.getResourceFromClassloader()` between flow-server-2.0.18 and 2.0.17 when loading flow-build-info.json, could that be a reason? Let me try to debug.

**Comment by mvysny** [comment]
Could it be that if the WAR is extracted by the AS locally to a working directory, then add-on jsons will have 1 `jar!` while app jsons will have 0 `jar!` ? I can see that in such case Vaadin 14.0.13 code would filter out all `flow-build-info.json`, reproducing this issue.

**Comment by joheriks** [comment]
@caalador It seems that the current approach of taking the first jar jives well with WebLogic, which repackages `flow-build-info.json` into a jar called `_wl_cls_gen.jar`. This jar is consistently returned as the first element by the classloader's `getResources(tokenResource)`. So this is already fixed by #7066.

@mvysny @SebastianKuehnau Easiest fixed by upgrading to Vaadin Platform 14.1.

**Comment by arehmann** [comment]
Now,
I am still getting the error with vaadin version 14.10.3 with Gradle Build
```
Task :createx-client:vaadinBuildFrontend FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':createx-client:vaadinBuildFrontend'.
> Command '/home/gitlab-runner/.vaadin/node/node /home/gitlab-runner/builds/e33ad99c/0/adsuite/createx/createx-client/node_modules/webpack/bin/webpack.js' failed with exit code 2: Hash: a19b8b433093230a577b
  Version: webpack 4.42.0
  Time: 539ms
  Built at: 07/24/2023 4:40:58 PM
   2 assets
  Entrypoint bundle = build/vaadin-bundle-78d25c2548823f5a09c3.cache.js
  Entrypoint bundle.es5 = build/vaadin-bundle.es5-a914753001883d[302](http://gitlab.alfa.de/adsuite/createx/-/jobs/93772#L302)221.cache.js
  [0] ../target/frontend/generated-flow-imports.js?babel-target=es6 4.46 KiB {0} [built] [failed] [1 error]
  [1] ../target/frontend/generated-flow-imports.js?babel-target=es5 4.46 KiB {1} [built] [failed] [1 error]
  
  ERROR in ../target/frontend/generated-flow-imports.js?babel-target=es6
  Module build failed (from ../node_modules/babel-loader/lib/index.js):
  Error: Cannot find package '@babel/plugin-proposal-object-rest-spread' imported from /home/gitlab-runner/builds/e33ad99c/0/adsuite/createx/createx-client/babel-virtual-resolve-base.js
      at new NodeError (/home/gitlab-runner/builds/e33ad99c/0/adsuite/createx/createx-client/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:203:5)
      at packageResolve (/home/gitlab-runner/builds/e33ad99c/0/adsuite/createx/createx-client/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:873:9)
      at moduleResolve (/home/gitlab-runner/builds/e33ad99c/0/adsuite/createx/createx-cl
```

**Comment by mcollovati** [comment]
@arehmann your issues look more related to #16905.
Take a look at the comments, especially https://github.com/vaadin/flow/issues/16905#issuecomment-1573413044, and see if you can find something that helps you

**Comment by mvysny** [comment]
@arehmann please try out the newest Gradle plugin 0.14.10.4 with Vaadin 14.10.4, hopefully the bug will be fixed there.
